FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# helloworld

# GET /
+ Response 200 (application/json)

        {"message":"Hello World"}

## hola [/hola]

### hola [GET]

+ Response 200 (application/json)

        {"message":"Hola !"}

## namaste [/namaste]

### namaste [GET]

+ Response 200 (application/json)

        {"message":"Namaste Test Demo !"}